### PR TITLE
Update to Rack API v0.6

### PR DESCRIPTION
**Pull request by cschol**
Update plugin to Rack API v0.6 incl. updated Makefile (reference: [Repair Team](https://github.com/VCVRack/community/issues/269)).

### CODE REVIEW

**Comment by KieranPringle** [comment]
Thanks @cschol, I really appreciate the time you have taken to do this. Unfortunately I'm going to hold off merging for now but leave this open. There are a few compilation errors I'm going to need to take a look at when I have some free time after a few weeks. I'd rather keep the head of master at a compilable revision even if it is only compatible with v0.5. All the same, I'm very grateful for the time you've taken to help me (and others!) out and you've definitely given me a head start on updating

**Comment by cschol** [comment]
No problem. Let us know if you need any more help.

**Comment by phdsg** [comment]
bump!
@KieranPringle now that 0.6 is live, i'm sure some people are missing the qube :)

**Comment by cschol** [comment]
Is there an  update on this PR? Thanks!

**Comment by KieranPringle** [comment]
@cschol I haven't made much progress, but I've not forgotten.

If someone else wants to fix the compilation errors and make it compliant with VCV v0.6 then I'm happy to verify locally, merge and release. Otherwise it may be a few more months before I have enough time to look at this again.

I know this isn't a great response, but this module was something for me to do over my Christmas break for a bit of fun and is not a massive priority for me. I'd prefer to be honest about that up front.

**Comment by KieranPringle** [comment]
Closing this in the end. Never ended up getting round to it, and now I'm starting over agan trying to make some v1 plugins.

Thanks all the same!

**Pull request closed without merging**
